### PR TITLE
Add preferred pronouns field

### LINKED ISSUE #324: Add a field for preferred pronouns
I would like to be able to put my preferred pronouns on my resume. For most users, this will be a bare string (e.g. `they/them/theirs`), but it should also be possible to add more complex data to it, such as:
- pronoun.is link (e.g. `http://my.pronoun.is/they`)
- an array of pronouns to which the theme can apply special formatting
  - example: `["they", "them", "theirs"]` becomes "they / them / theirs" or "they &bull; them &bull; theirs" depending on the theme

For inspiration, [this article][asana] discusses how Asana implemented preferred pronouns in profile settings.

[asana]: https://blog.asana.com/2018/05/product-process-adding-pronouns-asana-profile-settings/

### PR DESCRIPTION
**Pull request by aidan-fitz**
Add a `pronouns` field, which can be one of the following:
- a string, e.g. `they/them/theirs`
- a string array, e.g. `["they", "them", "theirs"]`
- an object with the following properties:
  - `content`, either a string or a string array
  - `url`, an optional link like http://my.pronoun.is/they

Resolves #324.

### CODE REVIEW

**Comment by antialias** [comment]
This is great! Would you be able to add some tests for this in [`test/basics.spec.js`](https://github.com/jsonresume/resume-schema/blob/v1.0.0/test/basics.spec.js)?

**Comment by fharper** [comment]
Any idea when this PR will be merged?

**Comment by heitorPB** [comment]
@aidan-fitz , could you fix the conflict, please?

**Comment by matthewstrasiotto** [comment]
👀

**Comment by thomasdavis** [comment]
Nah, this stuff way too political and just extra noise. Can put your pronouns in your summary if you need too.

**Comment by fharper** [comment]
True, it's not like everyone on the planet have a pronoun... oh wait!

**Comment by matthewstrasiotto** [comment]
With all due respect, your schema aims to standardize a way to describe oneself.

The way a person would like to be referred fits very, very naturally into this.

The choice to deny this pull request is in and of itself a political position that you've chosen to take, as is the the choice to delete comments that oppose it.

What's your problem with trying to make the community more inclusive?

**Comment by matthewstrasiotto** [comment]
So my question is-
This PR was approved, with changes requested, and you overrode this decision unilaterally to reject it on the basis that you think that making communication of pronouns more standard practise is unnecessary, presumably because it doesn't affect you.

Who is acting on politics here? Why did you override @antialias ?

**Pull request closed without merging**
