### PR TITLE
[WIP] Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by aloisdg**
Create a CONTRIBUTING.md (see #211)

### CODE REVIEW

**Comment by olivif** [comment]
@aloisdg made a few comments on the code, great initiative on this :smile:

**Comment by aloisdg** [comment]
Something like this to add somewhere?

## SectionName

* Keep it simple, stupid
* Don't repeat yourself
* You ain't gonna need this (?)
* Don't be dev-centric
* Think about localization

**Comment by PeterDaveHello** [comment]
Looks good :+1:

**Comment by stp-ip** [comment]
LGTM

**Comment by aloisdg** [comment]
close to move to v1

**Pull request closed without merging**
