### PR TITLE
Changes website to url

### PR DESCRIPTION
**Pull request by hkellaway**
Regarding Issue #148

### CODE REVIEW

**Comment by dbkaplun** [comment]
Can we get this merged please?

**Comment by olivif** [comment]
I am in for merging this :smile:

**Comment by olivif** [comment]
thanks @stp-ip , I closed the related issue :smile:

**Comment by chrisdotcode** [comment]
@olivif I might have said this already (going through ~50 issues in my notification queue right now), but henceforth, can you please target `v1.0.0` as the merge target? We don't like to touch `master`.

**Comment by olivif** [comment]
Yep, I think this might have been before that. We should add this to the contributing.md file so it's clear to everyone :smile:

**Comment by stp-ip** [comment]
Yeah that PR was before we made it clear we should go with v1.0.0.

**Pull request merged**
