### PR TITLE
Adds legal/IP object to schema

### LINKED ISSUE #14: Add a Patents section
Add a section for patents granted, similar to the awards section.

```
patents: [{
    patentNum: string,
    issueDate: string,
    title: string,
    abstract: string,
}], 
```

### PR DESCRIPTION
**Pull request by simonarnell**
Resolves #14

### CODE REVIEW

**Comment by stp-ip** [comment]
We had a huge discussion on what fields are necessary etc. The first consensus had a few more fields. Would the following work for your use case too?
```
    "legal": {
      "additionalItems": false,
      "description": "Specify your labels",
      "items": {
        "additionalProperties": true,
        "properties": {
          "applicationDate": {
            "description": "e.g. 2015-08-01 - [resume.json uses the ISO 8601 date standard]",
            "format": "date",
            "type": "string"
          },
          "description": {
            "description": "Give a brief description about this document",
            "type": "string"
          },
          "endDate": {
            "description": "e.g. 2020-09-03 - [resume.json uses the ISO 8601 date standard]",
            "format": "date",
            "type": "string"
          },
          "grantDate": {
            "description": "e.g. 2016-09-01 - [resume.json uses the ISO 8601 date standard]",
            "format": "date",
            "type": "string"
          },
          "idNumber": {
            "description": "e.g. JP2004369746A - [Add the application number or Id Number]  ",
            "type": "string"
          },
          "legalType": {
            "description": "e.g. Patent, Trademark, Copyright - [Give the type of this document]",
            "type": "string"
          },
          "name": {
            "description": "e.g. XYZ's patent on LZW compression, a fundamental part of the widely used GIF graphics format - [Add document name]",
            "type": "string"
          },
          "resources": {
            "additionalItems": false,
            "description": "Specify multiple resources with label",
            "items": {
              "additionalProperties": false,
              "properties": {
                "label": {
                  "description": "e.g Slides",
                  "type": "string"
                },
                "url": {
                  "description": "e.g. http://www.example.com/my-patent-slides/",
                  "format": "uri",
                  "type": "string"
                }
              },
              "type": "object"
            },
            "type": "array"
          }
        },
        "type": "object"
      }
```
https://github.com/resumic/schema/blob/master/schema.json#L285

**Comment by simonarnell** [comment]
@stp-ip what you proposed would mostly hit my requirements, it’d be nice to also record the patent assignee (for cases such as myself where I wrote the patent on behalf of my employer) and co-inventors. Take a look at my [site](https://simonarnell.github.io/cv.html) for what I am trying to achieve.

**Comment by fballiano** [comment]
From a first read of this PR the "legal" name wasn't really clear but I think this section of the schema would be a really nice idea.

**Comment by shamoons** [comment]
I like this, but the field should be `intellectual_property` as that term generally holds for copyrights, patents, etc.

**Comment by stp-ip** [comment]
In my view legal is the broader term and we do have the option to add a type.

The latest iteration on this would be:
```
"legal": {
      "additionalProperties": false,
      "description": "language section with summary and list of legal items",
      "properties": {
        "legal": {
          "description": "list of legal",
          "items": {
            "additionalProperties": false,
            "properties": {
              "applicationDate": {
                "description": "date of the application",
                "format": "date",
                "type": "string"
              },
              "coAuthors": {
                "description": "co-authors for this legal item",
                "items": {
                  "additionalProperties": false,
                  "properties": {
                    "name": {
                      "description": "full name",
                      "type": "string"
                    },
                    "url": {
                      "description": "url to link to mentioned person",
                      "format": "uri",
                      "type": "string"
                    }
                  },
                  "required": [
                    "name"
                  ],
                  "type": "object"
                },
                "type": "array"
              },
              "currentAssignee": {
                "description": "current entity or individual assigned to the legal item",
                "type": "string"
              },
              "description": {
                "description": "short description about the document",
                "type": "string"
              },
              "endDate": {
                "description": "end date",
                "format": "date",
                "type": "string"
              },
              "entity": {
                "additionalProperties": false,
                "description": "entity details",
                "properties": {
                  "description": {
                    "description": "entity's primary activity",
                    "type": "string"
                  },
                  "image": {
                    "description": "url or src of an image, photo or logo",
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "url": {
                    "description": "url of the entity website",
                    "format": "uri",
                    "type": "string"
                  }
                },
                "required": [
                  "name"
                ],
                "type": "object"
              },
              "grantDate": {
                "description": "date of the grant",
                "format": "date",
                "type": "string"
              },
              "identifier": {
                "description": "labeled identifiers",
                "items": {
                  "additionalProperties": false,
                  "properties": {
                    "id": {
                      "description": "ID/code of the identifier",
                      "type": "string"
                    },
                    "label": {
                      "description": "label of the identifier",
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "label"
                  ],
                  "type": "object"
                },
                "type": "array"
              },
              "legalType": {
                "description": "type of the document",
                "type": "string"
              },
              "name": {
                "description": "name of the document, patent, copyright assignment or the likes",
                "type": "string"
              },
              "previousAssignee": {
                "description": "previous entity or individual assigned to the legal item",
                "type": "string"
              },
              "resources": {
                "description": "multiple resources with label",
                "items": {
                  "additionalProperties": false,
                  "properties": {
                    "label": {
                      "description": "label of the resource",
                      "type": "string"
                    },
                    "url": {
                      "description": "url of the resource",
                      "format": "uri",
                      "type": "string"
                    }
                  },
                  "required": [
                    "url",
                    "label"
                  ],
                  "type": "object"
                },
                "type": "array"
              },
              "roles": {
                "description": "specific roles within or around this legal item - author might be assumed as default",
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "summary": {
                "description": "summary of achievements",
                "type": "string"
              }
            },
            "required": [
              "name",
              "entity"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "summary": {
          "description": "continous text summarizing or adding context to the full legal section",
          "type": "string"
        }
      },
      "type": "object"
    },
```

**Pull request closed without merging**
