### PR TITLE
add projects section

### PR DESCRIPTION
**Pull request by lilobase**
it can be used for very different type of personal or professional projects (like open source contribution).

### CODE REVIEW

**Comment by zafartahirov** [comment]
+1

**Comment by divyenduz** [comment]
+1

**Comment by aloisdg** [comment]
Nice idea. It fits with LinkIn.

**Comment by chrux** [comment]
awesome! +1, what we need :)

**Comment by mateusfreira** [comment]
+1

**Comment by chrisdotcode** [comment]
I believe we are already discussing this in some other issue. I won't close this until I (or somebody else helps me) find that issue.

**Comment by stp-ip** [comment]
@chrisdotcode I think you're looking for: #201

**Comment by chrisdotcode** [comment]
Thank you, sir.

**Pull request closed without merging**
