### PR TITLE
Add a Full Test Suite

### PR DESCRIPTION
**Pull request by evanplaice**
Test every aspect of the validator

### CODE REVIEW

**Comment by thomasdavis** [comment]
Jesus, solid effort! Great job.

**Comment by evanplaice** [comment]
Thanks. It's only 348 tests, lol. Like I said, I'm going to give the JSON Resume project some long overdue maintenance.

I have a couple questions
- can I add another repo to the org? I built a JSONResume VSCode extension
- can the validation code be moved to a separate `resume-validator` repo?

After these tests land, I'm going to rearrange the examples. Invalid examples are no longer necessary since that's already covered by the tests.

For the valid examples I'm going to
- rename complete.json -> complete.resume.json
- add empty.resume.json

The *.resume.json pattern is necessary for Intellisense in VSCode. IMO, It's a good idea to encourage users to follow the pattern.

**Comment by evanplaice** [comment]
If you want, I can remove the VSCode debug config (ie `launch.json`). It's really handy for running `*.spec.js` files one-at-a-time but I'm good with leaving it out to reduce cruft.

**Comment by thomasdavis** [comment]
> * can I add another repo to the org? I built a JSONResume VSCode extension

Your welcome to if it suits you.

> * can the validation code be moved to a separate `resume-validation` repo?

Sounds like a good idea. Perhaps `resume-validator`. 

> 
> For the valid examples I'm going to
> 
> * rename complete.json -> complete.resume.json
> * add empty.resume.json

Yep, makes sense. 


> The *.resume.json pattern is necessary for Intellisense in VSCode. IMO, It's a good idea to encourage users to follow the pattern.

**Comment by evanplaice** [comment]
FYI, my org access is limited. Can't create/transfer repos and no push access.

In general, I never push to master unless it's a trivial fix but it would be nice to be able to branch directly off the main repo rather than working from a fork.

**Comment by thomasdavis** [comment]
> FYI, my org access is limited. Can't create/transfer repos and no push access.
> 
> In general, I never push to master unless it's a trivial fix but it would be nice to be able to branch directly off the main repo rather than working from a fork.

Added to core contributors team and added repository creation access.

**Comment by evanplaice** [comment]
Thank you. Once my recent PRs pass review and land I'll start migrating validation stuff over to a new `resume-validator` repo.

I'll see if I can keep the existing API intact and throw a deprecation warning so users have time to change over before it's removed altogether.

**Pull request merged**
