### PR TITLE
formatting improved

### PR DESCRIPTION
**Pull request by ducin**
* ugly whitespaces removed (spaces between tabs)
* correct indentation of {
* removed empty newlines

### CODE REVIEW

**Comment by olivif** [comment]
Thanks @ducin, great initiative! I see the formatting has been revisited now, as this PR is quite old. I am closing for now, but feel free to have a look at the open issues if you would like to contribute further :smile:

**Comment by ducin** [comment]
Honestly, waiting 17 months for a reply doesn't encourage me to contribute further...

**Comment by aloisdg** [comment]
There is a nice activity nowadays.

**Comment by olivif** [comment]
@ducin I agree. I am doing my best to clean up these PRs here and make sure we get better at responding to issues and PRs. Won't happen overnight but we will get better :balloon:

**Comment by chrisdotcode** [comment]
@ducin Thanks for the contribution! It's true that the team wasn't as responsive for the past, but we're plenty active nowadays, promise.

**Pull request closed without merging**
