### PR TITLE
Canonical source URL

### PR DESCRIPTION
**Pull request by mwaclawek**
As suggested here: https://github.com/jsonresume/resume-schema/issues/28

### CODE REVIEW

**Comment by stp-ip** [comment]
LGTM. I would say it's save to merge. Only the description could be finetuned later on.

**Comment by opensourcegrrrl** [comment]
Rarely do people come back to get to the documentation bits. How about an action verb with a solid description before merging.

**Comment by chrisdotcode** [comment]
I think `canonical` is better than `url` - the former has explicit semantic meaning, while the latter doesn't.

**Comment by olivif** [comment]
@chrisdotcode  +1 for making it optional. 

@opensourcegrrrl +1 for updated description although I have no idea what would be better. 

Given the changes requested, we might need a new PR (or updates to this one if @mwaclawek is still around)

**Comment by aloisdg** [comment]
I personaly prefer "latest". As far as I know, it is widely used ([jQuery](http://code.jquery.com/jquery-latest.js) for example).

**Comment by chrisdotcode** [comment]
PRs are transient, issues are definitive. Let's all move to #28.

**Pull request closed without merging**
