### PR TITLE
Add multiple examples which are used as test cases

### PR DESCRIPTION
**Pull request by MarkBiesheuvel**
In another PR @olivif mentioned it would be nice to have more examples and test cases.

I have added two directories, one with valid resumes and one with invalid resumes.
The tester will use all of the files in these directories as test cases.

Feedback is welcome.

By they way, we might want to make some fields (like name) required, because right now an empty object is considered a valid resume.

### CODE REVIEW

**Comment by olivif** [comment]
amazing @MarkBiesheuvel , I will have a closer look soon 😄 

> By they way, we might want to make some fields (like name) required, because right now an empty object is considered a valid resume.

And you have just proven the value of this PR and this approach 👍

**Comment by thomasdavis** [comment]
https://travis-ci.org/jsonresume/resume-schema

That looks a lot better. Great work again.

There is an old discussion about required fields somewhere, the decision was to not enforce it because there was always potentially a situation where a certain field wanted to be skipped. (even name can sometimes be skipped when applying for jobs in secret)

I am also going to add the validator to the homepage

**Comment by olivif** [comment]
@thomasdavis homepage validation sounds awesome. 
@MarkBiesheuvel great stuff! very happy to see this 😄

**Comment by MarkBiesheuvel** [comment]
Thanks :smile:

**Pull request merged**
