### PR TITLE
Upgrading ZSchema and updating validator and tests to match. (v1)

### LINKED ISSUE #202: Upgrade z-schema
According to z-schema's readme, the new version(v3.x) is much faster than the 2.x, and v2.x is somehow a little bit out dated and old.

### PR DESCRIPTION
**Pull request by olivif**
Fixes #202 

Resubmit of #208 with correct v1.0.0 upstream :smile:

### CODE REVIEW

**Comment by stp-ip** [comment]
LGTM or is there anything missing due to the "in progress" label? cc @thomasdavis

**Comment by olivif** [comment]
thanks @stp-ip! Do let me know if there is anything missing. If not, feel free to merge me in :smile:

**Comment by olivif** [comment]
@stp-ip @thomasdavis merge? 😄

**Comment by PeterDaveHello** [comment]
@olivif since there are conflicts, would you please solve them first? So that I can merge this, thanks.

**Comment by stp-ip** [comment]
Seems the base repository is gone. Assuming we should just open another PR.

**Pull request closed without merging**
