### PR TITLE
#334 #349 add schema ref & clean up the samples

### PR DESCRIPTION
**Pull request by antialias**
re: ["cleanup the samples"](https://github.com/jsonresume/resume-schema/issues/349)
> mv /examples/valid/complete.json -> /sample.resume.json
> delete the rest, test/__test__ already contains a complete set of test fixtures
> remove resume.json from pkg.files
> add sample.resume.json to pkg.files

### CODE REVIEW

**Comment by antialias** [comment]
PTAL @evanplaice

**Comment by antialias** [comment]
done.

**Comment by antialias** [comment]
thanks! (I can't merge myself btw)

**Comment by evanplaice** [comment]
I know. I was replying to another comment of yours. If you want push access ask @thomasdavis.

**Comment by thomasdavis** [comment]
I've just added you to the core team @antialias 

Will get you guys added to the team page when I can (or add yourselves)

**Comment by antialias** [comment]
Well alright!

**Pull request merged**
