### PR TITLE
Change gpa to score to better reflect variance in international scoring systems

### LINKED ISSUE #288: Add Marking Scales for non-USA Courses.
GPA is meaningless for any countries outside of the USA.

The system of grading for Courses outside of the USA is very different from the USA standard of GPA and the A-B-C-D-E-F equivalent.

image
https://en.wikipedia.org/wiki/Grading_systems_by_country

The major problem is there's a veritable mass of confusing and non-compatible systems.

The EU tries to combat that by using the standard of ECTS to convert the local grading scale (where it takes whatever the original grading scales, divides them into 5 and places them in the equivalent locations on there own scale.)

But the ECTS is still not accepted in all EU countries, and is rarely used outside of the EU.

https://en.wikipedia.org/wiki/ECTS_grading_scale

image

### PR DESCRIPTION
**Pull request by DandyDev**
Fixes #288, supersedes #328

### CODE REVIEW

**Comment by DandyDev** [comment]
@stp-ip @thomasdavis can you have a look? I'd like to merge this asap.

**Comment by stp-ip** [comment]
Codewise this looks good. Still not sure we should be merging in breaking changes until we know what our overall direction is. If we agree, that the v1 branch is breaking and currently open for development and open to future breaking changes until we do a release, I'm happy to get this in now and discuss other options later :)

**Comment by thomasdavis** [comment]
LGTM. 

We will have some breaking changes, but minimal.

**Comment by DandyDev** [comment]
@stp-ip @thomasdavis as far as I'm concerned we can integrate breaking changes into the v1.0.0 branch. In the README we state that we adhere to the Semantic Versioning standard, and given that we haven't done an official (tagged) v1.0 release yet, breaking changes are fair game.

**Comment by thomasdavis** [comment]
@DandyDev Very true. We also will be only affecting thousands, not millions, let's bear the cost for now.

**Pull request merged**
