### PR TITLE
Upgrading ZSchema and updating validator and tests to match.

### LINKED ISSUE #202: Upgrade z-schema
According to z-schema's readme, the new version(v3.x) is much faster than the 2.x, and v2.x is somehow a little bit out dated and old.

### PR DESCRIPTION
**Pull request by olivif**
Fixes #202

### CODE REVIEW

**Comment by olivif** [comment]
Btw, I ran a separate test in a different branch to check our code coverage, to see how confident I should feel about these tests passing :smile: Looks like we are on 100% 

image

(this is using [Istanbul](https://www.npmjs.com/package/istanbul) and [codecov](https://codecov.io/) - on branch [rs-codecov](https://github.com/olivif/resume-schema/tree/rs-codecov))

**Comment by chrisdotcode** [comment]
Hey, @olivif, please choose branch `v1.0.0` as the merge target going forward.

**Comment by olivif** [comment]
@chrisdotcode yes, will do! I noticed master is ahead of v1.0.0 by a few commits so I wasn't sure. If this is a v1 candidate I can re-submit with v1 target :smile:

**Comment by chrisdotcode** [comment]
Yes, that would be ideal. master has some changes that @PeterDaveHello merged in, but nothing breaking. Master is currently upstream; we should be able to merge from it with impunity at this current moment.

**Comment by olivif** [comment]
excellent, thanks for letting me know. I have resubmitted now :smile: I'll close this one.

**Pull request closed without merging**
