### PR TITLE
Adding version field. Adding tests for metadata section.

### LINKED ISSUE #49: Resume.json should have revision history
We eventually want people to edit their resume's using a UI on the registry website etc

But we will run into problems with keeping resume.json's in sync.

e.g. If you edit it online and then publish from your local copy on your box you will override the changes you did on the registry.

We were thinking of adding a revision property which auto increments whenever you publish.

### PR DESCRIPTION
**Pull request by olivif**
Fixes #49

### CODE REVIEW

**Comment by chrisdotcode** [comment]
> "A version field which follows semver - e.g. v1.0.0"

Maybe this should read: What the `resume-cli` tool will use to determine which version of the schema this resume is in. And maybe it should include a warning to resume consumers that it isn't to be messed with?

In fact, what would you guys think of the version number being a main field in the schema? I think it's important enough, especially considering messing with it unintentionally could break your whole resume.

**Comment by stp-ip** [comment]
I think we discussed that and came to the conclusion, that it is not part of the data about the user and therefore meta data. Therefore it should go into the meta section. We could make it explicit, that meta.version and meta.url are not to be messed with.
We could have meta.X as meta data from the schema itself, then have meta.presentation.X and meta.tools.X? Just as an example. Not really the place to discuss that in-depth.

**Comment by chrisdotcode** [comment]
Yeah, okay, I get what you're saying. IMO, though, if it's not to be messed with, I think we can make an exception and put it in as a non-meta schema value. If the majority has already decided, though, then that's cool, too.

**Comment by stp-ip** [comment]
Done in #258

**Pull request closed without merging**
