### PR TITLE
Adding project section with Name and Description fields.

### PR DESCRIPTION
**Pull request by olivif**
Adding a projects section with Name and Description fields.

### CODE REVIEW

**Comment by chrisdotcode** [comment]
Thanks for this! We're not quite ready to merge it just yet, though.

We probably want to have a bit more discussion about what we should call this field.

Also, can you please PR into jsonresume:v1.0.0, not master? Thanks :)

**Comment by olivif** [comment]
Of course, I just noticed there was a lot of interest in the project section so I thought we should get the ball rolling with a code change :) I just noticed the build failed, missed a comma there, how can I run these tests locally? 

I will move the PR to v1. 

What else would we need for supporting the projects section? I see there is a lengthy discussion on the open issue :)

**Comment by chrisdotcode** [comment]
:+1: great initiative. In all honesty, I think we should flesh out all schema changes entirely, and *then* PR: we wouldn't want to waste dev time just to change the spec again afterward.

As for the tests, I believe those may need a revision and/or documentation. I've yet to look through them.

I'm actually going to create a new issue, aggregating all of the past issues discussion project, for ease of use.

**Comment by olivif** [comment]
Closing this for now as it needs a bit more work. Will probably be done in a new PR anyway :smile:

**Pull request closed without merging**
