### PR TITLE
Better dates

### PR DESCRIPTION
**Pull request by evanplaice**
The JSONSchema date format is too strict (ie YYYY-MM-DD). This new validation pattern is still ISO8601 compliant but allows for

- YYYY-MM-DD
- YYYY-MM
- YYYY

Refs: 
- Issue #142 
- this is a continuation of PR #150

### CODE REVIEW

**Comment by stp-ip** [comment]
Interesting solution. Due to various discussions in jsonresume we opted for strict data in Resumic and less strictness on the user side.

Meaning the validation is assuming 2020-01-01. The user should be able to input, YY, YY-MM or YY-MM-DD, but it would always default to a specific date. Say 2020 would default to 2020-01-01.

Looking forward to your thoughts.

**Comment by evanplaice** [comment]
@thomasdavis Requesting review since affects the schema (ie in a non-breaking way)

**Comment by evanplaice** [comment]
@stp-ip Technically, it's still possible to input invalid date ranges (ex 2001-19-39) due to limitations in RegEx parsing. This is a 'best effort' approach to validation.

If strict date validation is required, the value can be parsed using the built-in date format. Ex [ECMA262](https://tc39.es/ecma262/#sec-date-time-string-format) states that `Date.parse()` will work with all 3 of these formats. 

In practice, templates usually ignore date validation altogether and just display the string. Users will most likely edit `resume.json` by hand and don't want to be burdened with inputting the full `YYYY-MM-DD`.

IMO, the existing date format is one of characteristics of JSONResume that I like the least. After accumulating 15 years of professional work history, the last thing I want to be burdened with is trying to remember exact start/end dates. It's a resume, not a SF85P security clearance application.

As for defaulting the missing parts in a date, it looks sloppy. Most people who review a Resume don't care about the technical tradeoffs of the format used to create it. Optics matter and enabling users the flexibility to tailor their data to their own personal style is a net win.

**Comment by evanplaice** [comment]
In the bigger picture. My personal opinion doesn't really matter. The community asked for it in #142, and #150. In addition, if this lands it shouldn't require much effort to update it to accommodate #330 as well.

**Comment by evanplaice** [comment]
@stp-ip Did you want to block this PR to continue the discussion or is it good to merge?

**Comment by thomasdavis** [comment]
I think the originally arguments we made were;

1) If you wanted just a year, you can just do `2010-01-01` 
2) If we made the date string always the same, themes could more easily implement them 

But if Date.parse works on; 

```
YYYY-MM-DD
YYYY-MM
YYYY
``` 

Then I suppose it would be fine. 

It is kind of annoying so I do support this PR. 

Soooo, I'm going to say yes, let's approve it in.

**Pull request merged**
