### PR TITLE
Update validator to use CPS; add README.md example

### PR DESCRIPTION
**Pull request by matmar10**
Fixes issue #189

### CODE REVIEW

**Comment by thomasdavis** [comment]
Sweet, will review later today.

Awesome beard!

**Comment by matmar10** [comment]
Haha thanks :-) It's even longer, now.

**Comment by matmar10** [comment]
Nudge.

**Comment by thomasdavis** [comment]
Sweet, will review later today.

**Comment by thomasdavis** [comment]
jks

**Comment by thomasdavis** [comment]
Great fix and sorry for the delay.

**Pull request merged**
