### PR TITLE
Extra Sections

### PR DESCRIPTION
**Pull request by Keloran**
Extra sections for job usage so that we can show which technologies were used in particular job

### CODE REVIEW

**Comment by stp-ip** [comment]
Thanks for taking the time to contribute. Will look into the changes during the week and get back to you as soon as possible.

**Comment by stp-ip** [comment]
From going over it in short, we might need to go a bit more general. Language could actually mean spoken language or programming and systems is quite non generic and focused on IT only.
The general vision for jsonresume is to be a generic solution and therefore it might make more sense to have a tooling section instead of language and/or systems. Tooling could be much more widely used.
This is not yet thought through, just wanted to give a bit of feedback right away.

Further thoughts with "tooling". This could have the ability to have tooling with "name" and "description".

**Comment by Keloran** [comment]
fair enough

**Comment by stp-ip** [comment]
Just went through the current ideas and I think this could be done in a more generic way using highlights:
https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json#L127
So instead of saying you worked with "JS", "Go" etc. you could say: "Build awesome trading system using Go and JS"

Closing this for now. Happy to discuss any thoughts so.

**Comment by Keloran** [comment]
I do agree with the last statement, the problem I have with that is I always get asked the question, so what technologies did you use, and I feel a separate section for that would be better for my personal situation, and the main reason for that is a lot of the things that happen for me aren't "highlights" but I have done a varied amount of technologies in a single role

a good example of this, I worked on a booking system the company is known as a java house, but my entire time there was spent in the PHP projects, personally I would say the fact that I traveled to aquire a company a highlight, I would not say doing a ticketing system in PHP, Node and MySQL a highlight

**Comment by stp-ip** [comment]
Within the json-schema you can usually define additional properties. So it is possible, just needs some theme changes. From our point of view a generic standard, which is extensible is the goal.

**Comment by stp-ip** [comment]
In my opinion everything worthwhile within a specific job or project can be seen as a highlight. Still can be:
"Build internal ticketing system in PHP, Node and MySQL, which had xyz effect"

**Pull request closed without merging**
