### PR TITLE
Add url to education institution

### PR DESCRIPTION
**Pull request by vasileboris**

### CODE REVIEW

**Comment by shamoons** [comment]
What's the wait for this one? Seems super useful

**Comment by evanplaice** [comment]
@thomasdavis @stp-ip @antialias This is a non-breaking addition (waiting for 1.0 isn't necessary). Any arguments against including it now?

**Comment by thomasdavis** [comment]
LGTM

**Comment by shamoons** [comment]
Probably should have updated the CHANGELOG (looks outdated)

**Comment by evanplaice** [comment]
The change log is being migrated from README.md -> CHANGELOG.md. It'll show up once this https://github.com/jsonresume/resume-schema/tree/migrate-changelog branch lands.

**Pull request merged**
